using System.Net.Http.Headers;
using System.Net.Http.Json;
using Tatakae.Application.Contracts.Admin;
using Tatakae.Application.Contracts.Categories;
using Tatakae.Application.Contracts.Common;
using Tatakae.Application.Contracts.Coupons;
using Tatakae.Application.Contracts.Customers;
using Tatakae.Application.Contracts.Embroidery;
using Tatakae.Application.Contracts.Files;
using Tatakae.Application.Contracts.Inventory;
using Tatakae.Application.Contracts.Legal;
using Tatakae.Application.Contracts.Orders;
using Tatakae.Application.Contracts.Notifications;
using Tatakae.Application.Contracts.Payments;
using Tatakae.Application.Contracts.Products;
using Tatakae.Application.Contracts.Reviews;
using Tatakae.Application.Contracts.Security;
using Tatakae.Application.Contracts.Seo;
using Tatakae.Application.Contracts.Shipping;

namespace Tatakae.Web.ApiClients.Abstractions;

public interface IAdminApiClient
{
    Task<ResultDto<AdminDashboardDto>> DashboardAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<SeoAuditSummaryDto>> SeoAuditAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<NotificationDto>>> NotificationsAsync(AdminNotificationFilter? filter = null, CancellationToken cancellationToken = default);
    Task<ResultDto<NotificationDto>> CreateNotificationAsync(CreateNotificationRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<NotificationDto>> UpdateNotificationStatusAsync(Guid id, UpdateNotificationStatusRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<SeoRoutePolicyDto>>> SeoRoutesAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<ProductDetailDto>>> ProductsAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<ProductDetailDto>> ProductAsync(Guid id, CancellationToken cancellationToken = default);
    Task<ResultDto<ProductDetailDto>> CreateProductAsync(AdminProductRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<ProductDetailDto>> UpdateProductAsync(Guid id, AdminProductRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto> DeleteProductAsync(Guid id, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<InventoryVariantDto>>> InventoryAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<InventoryVariantDto>> AdjustInventoryAsync(Guid variantId, InventoryAdjustmentRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<CategoryDto>>> CategoriesAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<CategoryDto>> CreateCategoryAsync(AdminCategoryRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<CategoryDto>> UpdateCategoryAsync(Guid id, AdminCategoryRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto> DeleteCategoryAsync(Guid id, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<OrderDto>>> OrdersAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<OrderDto>> OrderAsync(Guid id, CancellationToken cancellationToken = default);
    Task<ResultDto<AdminOrderWorkflowDto>> OrderWorkflowAsync(Guid id, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<OrderStatusOptionDto>>> OrderStatusOptionsAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<OrderDto>> UpdateOrderStatusAsync(Guid id, AdminOrderStatusRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<AdminPaymentsDto>> AdminPaymentsAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<PaymentDto>> UpdatePaymentStatusAsync(Guid id, UpdatePaymentStatusRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<PaymentRefundDto>> RefundZarinpalAsync(Guid id, CreateZarinpalRefundRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<AdminProductReviewDto>>> ReviewsAsync(string? status = null, CancellationToken cancellationToken = default);
    Task<ResultDto<AdminProductReviewDto>> ModerateReviewAsync(Guid id, AdminReviewModerationRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<AdminProductQuestionDto>>> QuestionsAsync(string? status = null, CancellationToken cancellationToken = default);
    Task<ResultDto<AdminProductQuestionDto>> ModerateQuestionAsync(Guid id, AdminQuestionModerationRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<CustomerDto>>> CustomersAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<CouponDto>>> CouponsAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<CouponDto>> CreateCouponAsync(AdminCouponRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<CouponDto>> UpdateCouponAsync(Guid id, AdminCouponRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto> DeleteCouponAsync(Guid id, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<ShippingMethodDto>>> ShippingMethodsAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<ShippingMethodDto>> CreateShippingMethodAsync(UpsertManualShippingMethodRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<ShippingMethodDto>> UpdateShippingMethodAsync(Guid id, UpsertManualShippingMethodRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto> DeleteShippingMethodAsync(Guid id, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<FileUploadDto>>> MediaAsync(CancellationToken cancellationToken = default);
    Task<ResultDto> DeleteMediaAsync(Guid id, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<EmbroideryArtworkDto>>> AdminArtworksAsync(string? status = null, CancellationToken cancellationToken = default);
    Task<ResultDto<EmbroideryArtworkDto>> ModerateArtworkAsync(Guid id, AdminArtworkModerationRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<StorePolicyPageDto>>> LegalPagesAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<StorePolicyPageDto>> UpdateLegalPageAsync(string slug, UpsertStorePolicyPageRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<ContactMessageDto>>> ContactMessagesAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<ContactMessageDto>> UpdateContactMessageAsync(Guid id, UpdateContactMessageStatusRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<PermissionDto>>> PermissionsAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<AdminPageAccessDto>>> AdminPagesAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<AdminPageAccessDto>> UpdateAdminPageAsync(Guid id, UpsertAdminPageAccessRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<RoleSecurityDto>>> RolesAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<RoleSecurityDto>> CreateRoleAsync(UpsertRoleRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<RoleSecurityDto>> UpdateRolePermissionsAsync(Guid roleId, AssignRolePermissionsRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<AdminUserDto>>> SecurityUsersAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<IReadOnlyCollection<LoginAuditDto>>> LoginAuditsAsync(CancellationToken cancellationToken = default);
    Task<ResultDto<AdminUserDto>> CreateAdminUserAsync(CreateAdminUserRequest request, CancellationToken cancellationToken = default);
    Task<ResultDto<AdminUserDto>> UpdateUserRolesAsync(Guid userId, AssignUserRolesRequest request, CancellationToken cancellationToken = default);
}
